
server:
    port: 8080
spring:
    data:
        mongodb:
            host: mongo
            port: 27017
            database: test
    application:
        name: student-service
springdoc:
    api-docs:
          path: /student-docs